--- 
- name: Create and Upload UI-user-portal
  hosts: localhost
  tasks:
  - name: "Create S3 bucket if it doesn't exist"
    amazon.aws.aws_s3: 
      bucket: drscrumptious.com
      mode: create
      permission: public-read
  - name: "Configure S3 bucket to static website"
    s3_website: 
      name: drscrumptious.com
      state: present
      suffix: index.html
  - name: "Upload user portal to S3 bucket"
    community.aws.s3_sync: 
      bucket: drscrumptious.com
      file_root: ../dist/User-Portal/
      include: "*"
      permission: public-read